<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwnpdTI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwnpdTI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRwnpdTI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRwnpdTI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRwnpdTI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RwnpdTI',
    'container.build_id' => '5fdce81a',
    'container.build_time' => 1602432435,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwnpdTI');
