<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR7fxbck\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR7fxbck/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR7fxbck.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR7fxbck\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR7fxbck\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R7fxbck',
    'container.build_id' => '56517b0c',
    'container.build_time' => 1601921698,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR7fxbck');
